addons:
    apt:
        packages:
            - cppcheck

script:
    - (cd src/fsi && cppcheck --error-exitcode=1 --enable=performance,portability .)
    - (cd src/RBFMeshMotionSolver && cppcheck --error-exitcode=1 --enable=performance,portability .)
    - (cd src/tests && cppcheck --error-exitcode=1 --enable=performance,portability .)
    - (cd applications && cppcheck --error-exitcode=1 --enable=performance,portability .)
