#! /bin/bash

wclean src/fvPatchFields
wclean src/fvSchemes
wclean src/fsi
wclean src/RBFMeshMotionSolver
wclean applications/solvers/unsteadyPUCoupledFoam
wclean applications/solvers/consistentPimpleFoam
wclean applications/solvers/fsi/fsiFoam
wclean applications/solvers/fsi/fluidFoam
wclean applications/solvers/fsi/solidFoam
wclean applications/solvers/fsi/fsiFluidFoam
wclean applications/solvers/fsi/fsiSolidFoam
wclean src/tests/app
wclean src/tests/tubeflow
rmdepall
find . -name 'lnInclude' -exec rm -rf {} \;
