#!/bin/bash

set -e

wmakeLnInclude src/boundaryConditions
wmakeLnInclude src/fvSchemes
wmakeLnInclude src/fsi
wmakeLnInclude src/RBFMeshMotionSolver
wmakeLnInclude src/SRFModelAbs

wmake libso src/boundaryConditions
wmake libso src/fvSchemes
wmake libso src/fsi
wmake libso src/RBFMeshMotionSolver
wmake libso src/SRFModelAbs
wmake libso src/extraSolidBodyMotion
wmake libso src/bodyMotions
wmake libso src/bodyFsi
wmake all applications/solvers/bodyFsi
wmake all applications/solvers/consistentSolvers
wmake all applications/solvers/rbfDevelopment
wmake applications/solvers/unsteadyPUCoupledFoam
wmake applications/solvers/fsi/fsiFoam
wmake applications/solvers/fsi/solidFoam
wmake applications/solvers/fsi/fluidFoam

wmake applications/utilities/writeNonOrthogonality
wmake applications/utilities/addInitialRandomVelocity
wmake applications/utilities/mapMesh
wmake applications/utilities/writeSets
wmake applications/utilities/mapFields
wmake applications/utilities/yPlus

wmake src/tests/app
wmake src/tests/tubeflow

wmake applications/solvers/fsi/fsiSolidFoam
wmake applications/solvers/fsi/fsiFluidFoam
