#!/bin/bash

cd ${0%/*}

pwdstring=`pwd`
prefLocation=$WM_PROJECT_DIR/etc/prefs.sh

if [ -z "$FOAM_USER_SRC" ]; then
    echo "Creating FOAM_USER_SRC before compiling in $prefLocation"
    echo "# Setting up environment variable for FOAM-FSI" >> $prefLocation
    echo "export FOAM_USER_SRC=$pwdstring/src" >> $prefLocation

    echo ""
    echo "========================================================"
    echo "PLEASE RELOAD foam-extend-3.1 to ensure correct settings"
    echo "========================================================"
fi

set -e

wmakeLnInclude src/boundaryConditions
wmakeLnInclude src/fvSchemes
wmakeLnInclude src/fsi
wmakeLnInclude src/RBFMeshMotionSolver
wmakeLnInclude src/SRFModelAbs

wmake libso src/boundaryConditions
wmake libso src/fvSchemes
wmake libso src/fsi
wmake libso src/RBFMeshMotionSolver
wmake libso src/SRFModelAbs
wmake applications/utilities/addInitialRandomVelocity
wmake all applications/solvers/consistentSolvers
wmake applications/solvers/unsteadyPUCoupledFoam
wmake applications/solvers/fsi/fsiFoam
wmake applications/solvers/fsi/solidFoam
wmake applications/solvers/fsi/fluidFoam
wmake src/tests/app
wmake src/tests/tubeflow
