#!/bin/bash

set -e

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd fluid
cleanCase
cd -

cd solid
cleanCase
cd -

rm -rf fluid/0/solid
rm -rf fluid/system/solid
rm -rf fluid/constant/solid
rm -f fluid/constant/polyMesh/boundary
rm -f solid/constant/polyMesh/boundary
rm -f fluid/iterations-*.txt solid/iterations-*.txt
rm -f solid/constant/preCICE.xml system/decomposeParDict
