#!/bin/bash

killall -q -9 fsiFluidFoam ateles

set -e

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd fluid
rm -rf 0 precice_output
cp -r 0.org 0
rm -f *.foam iterResidualFile constant/polyMesh/boundary .*.address *.txt *.log
cleanCase
cd -

cd ateles
rm -rf log.* timing.res .*.address *.txt *.xml restart harvester *.pyc timing* *.log precice_output mesh
