#!/bin/bash

set -e

./clean

cd initialSolutionGaussPulse
wmake
cd -

. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp fluid/constant/preCICE.xml ateles/precice.xml

cd fluid
touch fluid.foam
runApplication blockMesh
runApplication renumberMesh -overwrite
runApplication checkMesh
runApplication initialSolutionGaussPulse
runApplication decomposePar
# mpirun -np 4 fsiFluidFoam -parallel &> log.fsiFluidFoam &
cd -

cd ateles
mkdir restart mesh
runApplication seeder
# mpirun -np 2 ateles &> log.ateles &
cd -

wait

# cd ateles
# ./postprocess
# cd -
#
# cd fluid
# runApplication reconstructPar
