#!/bin/bash

set -e

./clean

cd initialSolutionGaussPulse
wmake
cd -

. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp fluid/constant/preCICE.xml ateles/precice.xml

cd fluid
mkdir precice_output
touch fluid.foam
runApplication blockMesh
runApplication renumberMesh -overwrite
runApplication checkMesh
runApplication initialSolutionGaussPulse
runApplication decomposePar
mpirun -np 4 -output-filename log.fsiFluidFoam fsiFluidFoam -parallel &
cd -

cd ateles
mkdir restart precice_output
mpirun -np 2 /home/davidblom/repositories/apes/ateles/build/ateles ateles_euler.lua &> log.ateles &
cd -

wait

cd ateles
./postprocess
cd -

cd fluid
runApplication reconstructPar
