#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

#decomposePar
echo "Start running moveBodyFoamDavid on 1 processor"
runApplication moveBodyFoamDavid -DebugSwitches RBFInterpolation=1
#moveBodyFoamDavid -DebugSwitches RBFInterpolation=1
